#!/bin/bash
set -e

chown -R mysql:mysql /var/lib/mysql
mysql_install_db --user mysql > /dev/null

DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-""}
DB_DATABASE=${MYSQL_DATABASE:-""}
DB_USER=${MYSQL_USER:-""}
DB_PASSWORD=${MYSQL_PASSWORD:-""}
DBD_ARGS=${MYSQLD_ARGS:-""}
DB_HOST=`/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`


tfile=`mktemp`
if [[ ! -f "$tfile" ]]; then
    return 1
fi

cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
UPDATE user SET password=PASSWORD("$DB_ROOT_PASSWORD") WHERE user='root';
EOF

if [[ $DB_DATABASE != "" ]]; then
    echo "CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile

    if [[ $DB_USER != "" ]]; then
        echo "GRANT ALL ON \`$DB_DATABASE\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> $tfile
    fi
fi

/usr/sbin/mysqld --bootstrap --verbose=0 $DBD_ARGS < $tfile
rm -f $tfile

supervisord -n
exec /usr/sbin/mysqld $DBD_ARGS
